tap "homebrew/cask"
tap "homebrew/cask-fonts"

cask "alacritty"
cask "rectangle"
cask "keepingyouawake"
cask "font-fira-code"

brew "coreutils"
brew "tmux"
brew "vim"
brew "neovim"
brew "node"
brew "go"
brew "yarn"
brew "git"
brew "git-lfs"
brew "git-delta"
brew "imagemagick"
brew "tree"
brew "ag"
brew "wget"
brew "tig"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "zsh-history-substring-search"
brew "translate-shell"
brew "trash"
brew "tldr"
brew "htop"
brew "jq"
brew "jump"
brew "httpie"
brew "watch"
brew "lazygit"
brew "fzf"

